name: NuGet Build & Deploy

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    env:
      Solution_Name: HandlebarsTextbox.sln
      Winforms_Project: .\src\HandlebarsTextbox.Winforms\HandlebarsTextbox.Winforms.csproj
      Avalonia_Project: .\src\HandlebarsTextbox.Avalonia\HandlebarsTextbox.Avalonia.csproj
      Configuration: Release

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Pack WinForms project
      run: dotnet pack $env:Winforms_Project -c $env:Configuration

    - name: Pack Avalonia project
      run: dotnet pack $env:Avalonia_Project -c $env:Configuration

    - name: Push WinForms package to NuGet.org
      run: dotnet nuget push .\src\HandlebarsTextbox.Winforms\bin\Release\HandlebarsTextbox.Winforms.*.nupkg --api-key "$env:NUGET_TOKEN" --source https://api.nuget.org/v3/index.json --skip-duplicate
      env:
        NUGET_TOKEN: ${{ secrets.NUGET_KEY }}

    - name: Push Avalonia package to NuGet.org
      run: dotnet nuget push .\src\HandlebarsTextbox.Avalonia\bin\Release\HandlebarsTextbox.Avalonia.*.nupkg --api-key "$env:NUGET_TOKEN" --source https://api.nuget.org/v3/index.json --skip-duplicate
      env:
        NUGET_TOKEN: ${{ secrets.NUGET_KEY }}
